### ISSUE TITLE
Audit of Rule 2 takes decent amount of time and causes a timeout randomly

### ISSUE THREAD

**Issue by rvantonisse** [Siteimprove/alfa#101]
Running some new audits I stumbled upon a timeout, running audit on the same adress severall times made the audits run successfully and falsy at random. 

I timed the audits and for rule 2 they take up to 100ms for auditing 5 applicables, 700ms for 13 applicables.

For "https://www.accessibility.nl/wai-tools/validation-test-sites/amazon.com/
" the audit times out allways

For "https://www.accessibility.nl/wai-tools/validation-test-sites/hp-a3-multifunction-printer-and-copier-hpr-official-site/" timed out once a while. outcome was passed when the audit did not timeout.

Let me know if more info is needed.

**Comment by kasperisager** [comment]
While audits don't implement a timeout policy, the scraper does. What you're seeing is therefore the scraper timing out, which can fortunately be solved by configuring a higher timeout. The default is 10 seconds which is a little too optimistic for both of those sites; I was able to load the former in ~17 seconds while the latter loaded in ~9 seconds.

**Comment by rvantonisse** [comment]
Ok timeout is scraper related, thanks.

This solved auditing these sites.
