### ISSUE TITLE
`isVisible` should not consider descendants of media elements as visible

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#1017]
```html
<video src="foo">
  Hello
</video>
```
The text is only used for legacy browsers without support for `<video>` and isn't visible otherwise. Since all major browsers currently support the element, we should consider the text as invisible.
Other media elements are likely affected in the same way.

**Comment by elenamongelli** [comment]
Looking at HTML multimedia, seems that only `audio` is affected as well. There is also `track`, but it's a child of `audio` or `video`
