### ISSUE TITLE
Implement remaining HTML grammar insertion modes

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#113]
Fill in the blanks:

https://github.com/Siteimprove/alfa/blob/b4a71b15d541e1eec4d199ee0bef23157e3affce/packages/alfa-html/src/grammar.ts#L117-L220

**Comment by NiclasHedam** [comment]
Some work done on the [feature-insertion-mode](/siteimprove/alfa/tree/feature-insertion-modes) branch.

**Comment by kasperisager** [comment]
The HTML package has been removed for the time being so I'll close this.
