### ISSUE TITLE
Investigate caching DOM tree traversal operations

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#1144]
Since #283 (see discussion in #204), DOM nodes are "free floating" until they are frozen, e.g. by attaching them to parent. This notably ensure that **sub**trees never change. However, **super**trees may change by attaching the (current) root into another node.
As a consequence, tree traversal functions cannot be changed because `node.ancestor` can change. However, several of these are fairly costly and called often…

However, in our most frequent use case, the DOM tree does not change (it is just read from the JSON). So we could introduce a "global frozen" state and cache traversal functions when the node is part of a globally frozen tree. Globally frozen could either be stored on each node, or just be equivalent to `node.root().frozen`. (in turn, `node.root()` would need to be always cached to be fast, but can change 😖 Double rooting could work (`node.root() = {node._root = node._root.root(); return node._root}`) and be fast enough 🤔 ).

Care must be taken for the traversal options in the cache. See #1132 (and `.path()` should also hook onto the globally frozen state).
When building a `Document` from JSON, it would be globally frozen (or maybe only as part of a `Page.from()` build…) Leave an option to build an non-frozen one…

We've seen a page with ~9000 CSS rules about `a` name (!), including ~4000 with sibling selectors (`div + a`).
Matching these requires to find the preceding element, which in turn requires the list of sibling which can be a bit expensive… and is done 4000 times for each link on the page 🙈

**Comment by kasperisager** [comment]
Hi @Jym77, it's been a while! 👋 I couldn't help but notice that the actual problem you're seeing would be completely remedied by style sharing: #19

Hope everyone is well!

**Comment by Jym77** [comment]
Hi @kasperisager Thanks. I was indeed also thinking into that without being sure. Would certainly be much cleaner…

**Comment by Jym77** [comment]
`node.preceding` and `node.following` seem to be fairly costly at build time due to `Sequence.reverse` and `Sequence.skipUntil` actually forcing the evaluation (up to the match for the latest). So they both would benefit from caching, independently from style sharing.
`node.preceding` is also on a hot path for matching sibling selectors…

Given that our DOM trees are downward frozen, it is not possible to add siblings to a node who already has a parent, so this caching is rather safe to do.
