### ISSUE TITLE
Accessible name from `aria-label` is not computed correctly in case of inline elements

### ISSUE THREAD

**Issue by zsofitoth** [Siteimprove/alfa#1203]
```HTML
<span role="presentation" aria-label="Eli">
    <span aria-label="Garaventa">Zambino</span>
</span>
<span>the weird.</span>
```

The accessible name should be:
_My name is Eli the weird._
It is instead: _My name is Elithe weird._

[Link to Testable Statement](https://www.w3.org/wiki/AccName_1.1_Testable_Statements#Name_from_content)

**Comment by 2biazdk** [comment]
I've encountered this issue.

I have this button:
```
<button type="button" aria-labelledby="dropdown-button-148" id="dropdown-button-148">
    <div>List of fruits</div>
    <div>
        <p>Blueberry</p>
        <p>It’s a berry and it’s blue.</p>
    </div>
</button>
```

But Alfa tells me the visible text and the Accessible Name do not match,

Alfa sees the visible text as: "`list of fruits blueberry its a berry and its blue`"
Alfa sees the Accessible Name as: "`list of fruitsblueberryits a berry and its blue`"

**Comment by Jym77** [comment]
Seems to be clarified in https://github.com/w3c/accname/pull/168
