### ISSUE TITLE
SIA-R53 Headings are structured is too strict for US government organizations following Trusted Tester

### ISSUE THREAD

**Issue by offsetChris** [Siteimprove/alfa#1252]
[The 508 Trusted Tester](https://section508coordinators.github.io/TrustedTester/structure.html) program says the following regarding headings:

> A heading level 1:
> 
> Is not required
> 
> Can be used more than once on a page
> 
> Is not required to match the page title
> 
> The level of headings may not always be in sequence but may be valid as it relates to the visual structure/importance communicated by visible headings on the page. For example, an `<h2> `heading may be used for a navigation structure that precedes an `<h1>` title on a page. It is also acceptable to have `<h3>` then `<h5>` without an `<h4>` in between.

The US Government standard for conformance testing clearly differs from the ACT testing process. Could there be a way to help both types of testing requirements?

**Comment by Jym77** [comment]
SIA-R53 is only a Best Practice, not a WCAG failure of any sort, indeed.
It is based upon:
* [HTML specs about outlines](https://html.spec.whatwg.org/multipage/sections.html#headings-and-outlines):
  > Each [heading](https://html.spec.whatwg.org/multipage/sections.html#concept-heading) following another [heading](https://html.spec.whatwg.org/multipage/sections.html#concept-heading) lead in the [outline](https://html.spec.whatwg.org/multipage/sections.html#outline) must have a [heading level](https://html.spec.whatwg.org/multipage/sections.html#heading-level) that is less than, equal to, or 1 greater than lead's [heading level](https://html.spec.whatwg.org/multipage/sections.html#heading-level).

  (which is exactly what the rule test)
* [WCAG technique H69](https://www.w3.org/WAI/WCAG21/Techniques/html/H69):
  >  Skipping levels in the sequence of headings may create the impression that the structure of the document has not been properly thought through or that specific headings have been chosen for their visual rendering rather than their meaning. Authors are encouraged to nest headings hierarchically.

None of these are required for WCAG, indeed, hence the rule is a Best Practice, i.e. what Siteimprove recommends.

From this point of view, the rule works as intended.
