### ISSUE TITLE
Investigate layout system

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#1256]
The lack of layout system is causing problems in several places. We've investigate earlier possible solutions without being very successful (#183, #756). This issue will gather known problems due to lack of layout, and possible way to improve the situation.

---
- `getColors` (R66, R69): without layout, it is impossible to find if absolutely positioned elements are on top or below other elements. This has led to problems with carrousels (#758, #907), which was solved by asking extra questions, way too many, and we try to reduce that number (#1118, #1130, #1253). The current solution is still not perfect…
- `getColors` (R66, R69): with a layout system, and information about external images, we could automatically resolve background color of text on top of images, or better handle gradients, …
- R83: a lot of false positives are created by having a small button "cut" by the `overflow` on the `<body>` element or similar large container. The rule still produces a lot of true positives and thus still has a lot of value…
- `isVisible`: off screen text is poorly detected, we rely on heuristic but fail to see that some text is moved off screen. Notably with `position: absolute; top: -999px`, or `text-indent: -999px` and a small enough text.
- `hasSameForegroundAsBackground` simply ignore positioning. Again with carrousels or similar constructions where a background image is interposed below text, it will ignore it and see the background color through it. This may result in incorrectly considering that "white text on top of interposed image on top of (default) white background" is invisible as it is white-on-white.

---
Two possible solutions are considered, none of them being easy to implement…
- The approach in #756 would be to have data enriched with layout information (e.g., boxes for each element). The onus of producing the layout is put on the data producer and Alfa "simply" consume it. While this approach is relatively low weight, it puts some work on other people; it also ties the audit with the device that was used to create the layout information and rules that rely on layout cannot be checked with a different `Device` (e.g. to trigger different media queries, …) while they are the most likely to benefit from it.
- The other approach is to have Alfa build all layout information itself. This requires having data about image sizes, or fonts… and add a typesetting algorithm. This is a huge amount of work 😕

**Comment by dan-tripp-siteimprove** [comment]
For SIA-R83 ("Text nodes are not clipped when text is resized") I would like to add this "catch-all" case, which is a source of "real false positives": 
**When the container is large enough to contain the target element.**
In other words: 
- The overflow CSS properties exist and cause alfa to flag the element, but... 
- We can confirm by manual testing that overflow never happens on the page under any desired combination of zoom level / zoom type (text-and-images vs. text-only) / viewport size.
