### ISSUE TITLE
Media rules (and Applicability) could auto-detect embedded play button and `autoplay` attribute

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#1326]
When the `<audio>` element has `controls`, Alfa could assume that it includes a play button and avoid asking the question.

Alfa could use the `autoplay` attribute and assume the audio is playing.

(R49 is already doing that)

**Comment by Jym77** [comment]
Media rules are the 20s and 30s.
There are shared Applicabilities and Expectations.

**Comment by rcj-siteimprove** [comment]
According to [Mozilla autoplay guide](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide) most browsers block autoplay unless certain conditions are met for example if the audio is muted it won't be blocked (`<audio controls autoplay muted>...`).

Do we still want to assume it's playing based on this? We could also refine it to also look for `muted`. The other conditions listed doesn't seem to by something Alfa can know, so I'm wondering if we should still ask questions unless `muted` is present.

@Jym77

**Comment by Jym77** [comment]
Yes, I thing we should assume it plays when `autoplay` is present.
It, at least, indicates intention by author to have it autoplay if possible, so it is also an author responsibility to provide means to stop the media.
This goes together with some [recent ACT rules discussion](https://github.com/act-rules/act-rules.github.io/issues/2030) about the topic of autoplay.
