### ISSUE TITLE
Generate API documentation for all packages

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#135]
Approaches tested so far:

- [**TypeDoc**](https://github.com/TypeStrong/typedoc). Currently not possible due to: https://github.com/TypeStrong/typedoc/issues/923

- [**Documentation.js**](https://github.com/documentationjs/documentation). Seems to straight up not work.

- [**API Extractor**](https://github.com/microsoft/rushstack/tree/master/apps/api-extractor). Currently not possible due to: https://github.com/microsoft/rushstack/issues/1029. Also does not support merged namespaces, which we use quite a bit.

- [**Compodoc**](https://github.com/compodoc/compodoc). Does not support generating Markdown output.

**Comment by kasperisager** [comment]
This has become especially relevant now that we've published all packages to GitHub; it should be easy for consumers to discover the different packages and the APIs they expose. API Extractor currently seems like the best candidate, but is still not a viable option due to the reasons listed above.

Also, we should keep an eye on https://github.com/TypeStrong/typedoc/issues/1266.

**Comment by kasperisager** [comment]
Work on this is being tracked in #290.

**Comment by Jym77** [comment]
To ease the entry cost into Alfa, we could group packages by similar areas of interests. I see 4-5 groups currently:
- Core functionality: map, list, predicate, equatable, …; these are packages that implement basic data type and interfaces. They are not specific to Alfa and could be in any project.
- Data manipulation: aria, dom, style, …; these are packages about understanding our data and manipulating it. They could be in any project manipulating HTML documents.
- ACT implementation: act, rules, …; these are the stuff Alfa really wants to do. They are specific to what we do with it and are essentially the tip of the iceberg that "casual" users might be interested in.
- test frameworks: chai, cherio, react, …
- utilities: scrapper, crawler, …

Having such high-level grouping could help navigating the 80 packages we have… Typically, it is fairly obvious (from the name) what `alfa-dom` is about, but if one doesn't know about it, it's hard to locate in a long list of alphabetically ordered packages…

Not sure how this fits in auto-generated doc. Maybe this could be auto-generated from package description?
Not sure if it would be possible to show that grouping at https://github.com/orgs/Siteimprove/packages?repo_name=alfa or a similar place…
