### ISSUE TITLE
Getting invalid JSON error when installing

### ISSUE THREAD

**Issue by jrpool** [Siteimprove/alfa#1421]
In about 1 out of 2 attempts to install alfa, I get this error:

invalid json response body at https://npm.pkg.github.com/@siteimprove%2falfa-result reason: Invalid response body while trying to fetch https://npm.pkg.github.com/@siteimprove%2falfa-result: Socket timeout

**Comment by Jym77** [comment]
🤔 That sounds like a Github registry issue (especially if it works sometimes).
Is that a recent problem or has it been here for a long time (i.e. could it be a temporary Github problem)?
And is it only `alfa-result` that is troublesome, or sometimes other packages too?

I'm not seeing any problem like that in the several projects I have that depend on Alfa.

Let me know if the problem persists or disappear. I'm not really sure whether I can do something on my end, though.

**Comment by Jym77** [comment]
@jrpool Are you still seeing this problem?
