### ISSUE TITLE
Provide browser specific equivalents of querySelector/querySelecorAll

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#145]
`querySelector` and, especially, `querySelectorAll` could take a browser specific "predicate" (returning a `BrowserSpecific<boolean>`) to avoid repeated applicabilities like
```js
filter(querySelectorAll(document, document, isElement), element => {
            return map(isLink(element, document, device), isLink => {
              if (!isLink) {
                return false;
              }

              return isExposed(element, document, device);
            });
          })
```

**Comment by kasperisager** [comment]
This should really be separate from the core `querySelector(All)` functions as these are not inherently browser specific. Let's refine this further at some point though.

**Comment by kasperisager** [comment]
I'll go ahead and close this as it has been dealt with on the `develop` branch.
