### ISSUE TITLE
Improvements to watch script

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#146]
While strict checks for actual publication is awesome, it can get in the way when using `yarn start` to watch files. Notably because it forces to switch focus to unrelated code improvements and away to the actual code being developed or debugged. Notably:
- unused declarations
- non-alphabetic imports
could be warnings rather than errors.

Also, if it could automatically run the test file when the source code is changed, that wuld be great 😃

**Comment by kasperisager** [comment]
> Also, if it could automatically run the test file when the source code is changed, that wuld be great 😃

It already does 😉

**Comment by Jym77** [comment]
Arf… Being confused by the fact that it only display stuff if the test fails 😕

**Comment by kasperisager** [comment]
Let's have a think about this in light of #170.

**Comment by kasperisager** [comment]
Seeing how the compiler option for unused local declarations has been switched off and the linter setup is being redone, let's continue the discussion in #179.
