### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#155]
- [ ] @kasperisager Add tests for the many CSS value types, especially their parsing routines.

**Comment by kasperisager** [comment]
For reference, test coverage can be measured with https://github.com/bcoe/c8.

**Comment by kasperisager** [comment]
- [ ] @kasperisager Add tests for the many CSS value types, especially their parsing routines.

**Comment by kasperisager** [comment]
Closing this as there's no obvious exit condition. If we feel it's needed, we can open specific issues for the individual subsystems.
