### ISSUE TITLE
Alfa components not being published to npmjs?

### ISSUE THREAD

**Issue by wittjeff** [Siteimprove/alfa#1676]
We are trying to use Testaro (https://github.com/cvs-health/testaro) which uses @siteimprove/alfa-playwright, but we get a 404 error trying to load the package. Looking at npmjs.com, I see some of the Alfa packages, but _not_ several of the integration packages. There might also be a suspicious bias toward the top end of the alphabet in the @siteimprove/alfa-* packages that are available. I wonder if a deployment script failed?

**Comment by wittjeff** [comment]
Ahhhhh that's what the token is for! It all comes together now. :) Thanks!

**Comment by Jym77** [comment]
@wittjeff Update on this:
The 25 packages limit is a npmjs security measure for new users. It seems that we are now past that limit and packages are correctly published there 🎉 (all 104 packages of this and `alfa-integrations` repository are there now, with versions 0.93.0 / 0.73.2 which are the respective latest ones).

I'll monitor the situation a bit longer before fully automating my publication process, but things seem to work. I'm closing this issue now.
