### ISSUE TITLE
Prevent eager evaluation of expectation conditions

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#182]
Looking over the changes in #174 it struck me that the newly introduced `expectation()` helper forces us to eagerly evaluate all expectation conditions which is not desirable. Consider something like this:

```ts
expectation(
  cheapCondition(target),
  Pass,
  expectation(
    expensiveCondition(target),
    Pass,
    Fail
  )
);
```

The above would result in both `cheapCondition()` and `expensiveCondition()` being evaluated, even though the latter can be skipped if `cheapCondition()` is `true`. This can be prevented in two ways: Use `Predicate.fold()` (boolean or trilean) or make the `expectation()` helper accept thunks. Using `Predicate.fold()` is what was previously done and would look like this:

```ts
fold(
  cheapCondition,
  target,
  () => Pass,
  () => fold(
    expensiveCondition,
    target,
    () => Pass,
    () => Fail
  )
);
```

Alternatively, the `expectation()` can be changed to accept thunks which is arguably the cleaner approach:

```ts
expectation(
  cheapCondition(target),
  () => Pass,
  () => expectation(
    expensiveCondition(target),
    () => Pass,
    () => Fail
  )
);
```

**Comment by Jym77** [comment]
Yes. The real reason to use thunk in these is for being lazy which I completely forgot when implementing the `expectation` helper.

I'm in favour of having `expectation` accept thunks as I think the syntax (and name) is more intuitive than `fold`. I also think it should accept both thunks and values to allow
```javascript
expectation(
  condition(target),
  Ok.of("Yeah!"),
  () => expectation(
    condition2(target),
    Ok.of("Good enough"),
    Err.of("Oh no!")
```
where the thunks would look very clumsy when we have immediate values.

**Comment by kasperisager** [comment]
My concern with accepting both is that it makes it possible to do the wrong thing. If only thunks are accepted, there's no footgun lying around.

**Comment by Jym77** [comment]
Good point.

**Comment by kasperisager** [comment]
@Jym77 Turns out this is actually causing an exception to be thrown in SIA-R49:

https://github.com/Siteimprove/alfa/blob/6d4357f2b591f7b9e70bc6484ee24e1c1ed3aa8a/packages/alfa-rules/src/sia-r49/rule.ts#L82-L96

The left branch is only supposed to be evaluated when `mechanism.isSome()` is true as it will otherwise attempt to call `.get()` on `None`.
