### ISSUE TITLE
Implement ARIA presentational roles conflict resolution

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#184]
This bit of the ARIA spec is currently not considered when we compute roles for elements: https://www.w3.org/TR/wai-aria/#conflict_resolution_presentation_none

**Comment by Jym77** [comment]
Some tests on how (some) browsers do it, as well as guestimate of their internal rules: 
https://github.com/act-rules/act-rules.github.io/wiki/Tests-on-Presentational-role-Conflict-resolution
