### ISSUE TITLE
Redesign the @siteimprove/alfa-assert package

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#270]
After having noodled around with the current `@siteimprove/alfa-assert` package and its different offspring, `@siteimprove/alfa-jasmine`, `@siteimprove/alfa-jest`, et. al. it dawned on me that the current approach to accessibility assertions just doesn't work. The approach can be summed up as:

1. Given some input, such as a React node or an Angular test fixture, transform it into a `Page` object.
2. Run all available accessibility rules on the resulting `Page` object.
3. Either:
    - If any of the rules produce a failed outcome, grab the first failed outcome and pass an `Err` result.
    - Otherwise, pass an `Ok` result.
4. If an `Err` result was passed, present it using whatever means are appropriate for the context.

Of these, step 1 is the only one I'm really satisfied with.

Step 2 is problematic because not every rule will make sense to run in every conceivable context. For example, if I'm testing a component in isolation, it doesn't matter if the document has a `<title>` element as I'm not testing an entire document. If the component I'm testing is sufficiently atomic, it also doesn't matter that the component might be missing its required context role because it hasn't yet been put into a larger context. 

Step 3 is problematic as it risks concealing a large portion of failures that won't show up until the currently relevant failure has been fixed. This means re-running all the tests before additional failures become known rather than having a readily available view of _all_ failures.

Step 4 is problematic because it has proven incredibly difficult to present the kind of information we want to present for accessibility issues within the rather constrained test output of the various frameworks and libraries we've prototyped integrations for. Some of them only allow for very short messages, such as "expected target to be accessible", before things get unwieldy.

So, we need an new approach to this entire thing. With the points above in mind, I've identified the following criteria that a solution must meet:

1. The assertion output should be restricted to "something went wrong" or "everything is good" as this ensures we can present it across all the different frameworks and libraries we would want to integrate with. We shouldn't try to present the actual failures as part of the normal test output, which leads to the second point...

2. ...that all failures should be made available externally by relying on the existing formatter mechanism used by the CLI, i.e. `alfa-formatter-*` packages. This way, the actual failures can be presented to users using whatever tools they would normally use for digesting the outcome data.

**Comment by Jym77** [comment]
To fix Step 2., we also need a possibility for more granular tests than "use all rules". And because rules are added often, that probably mean high level selectors ("page", "component", "`<button>`", SC, … need to figure out which kinds of granularity are wanted) to which rule can "subscribe".

---
Something somewhat orthogonal but which might prove useful for the whole thingy is the new Diagnostics. Maybe some rules outputting more than an error message can help presenting relevant information to users.

**Comment by kasperisager** [comment]
Here's a design I started playing with today:

```ts
const { expect } = Asserter.of([...rules], {
  // The path to output failed outcomes to
  output: "results.json",

  // The format to use for outputting failed outcomes
  format: Formatter.load("json").get(),

  // Whether errors should be thrown or returned
  throw: true,
});

await expect(target).to.be.accessible();
```

The idea is to have an `Asserter` class that is responsible for the construction and configuration of `Assertion` classes returned by the bound `expect` method. This way, the rules that should be part of the audit and where outcomes are written to is configured up front to keep the rest of the interface clean. We might also want to provide a way of overriding the base `Asserter` configuration in the individual assertion method, such as `.accessible()`.

**Comment by kasperisager** [comment]
I refined this a little more and it now looks like this:

```ts
const { expect } = Asserter.of(
  [...rules],
  [
    Handler.persist(
      // The path to output failed outcomes to
      () => "results.json",

      // The format to use for outputting failed outcomes
      Formatter.load("json").get()
    )
  ],
  {
    // Whether errors should be thrown or returned
    throw: true,
  }
);

await expect(target).to.be.accessible();
```

The `Handler` class is responsible for _handling_ failed outcomes and passing along an error message that is incrementally constructed by the different handlers. One such handler, `Handler.persist()`, writes failed outcomes to disk and adds a bit to the error message about where the outcomes were written:

```console
$ mocha

  page.html
    1) should be accessible

  0 passing (710ms)
  1 failing

  1) page.html
       should be accessible:
         2 failed outcomes found, see the full report at test/outcomes/page.spec-1592992823277.json

**Comment by kasperisager** [comment]
I've been some progress on this but will slate it for now as it has turned out to be a little more involved than I initially thought.

**Comment by kasperisager** [comment]
The progress I've made on this is now available in #287.

**Comment by kasperisager** [comment]
This will be my focus for next week.

**Comment by kasperisager** [comment]
That didn't happen 😔 I'll keep this on the back burner for the time being.
