### ISSUE TITLE
Ideas for parser quality of life improvement

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#292]
* n-ary `either` Would make things like https://github.com/Siteimprove/alfa/blob/master/packages/alfa-css/src/value/color.ts#L55-L61 much nicer to write and read. Need that all parsers args return the same type.

* helpers functions in alfa-css, things such as https://github.com/Siteimprove/alfa/blob/style-custom-property/packages/alfa-css/src/value/color/var.ts#L121-L122 Could also use a `parseFunctionCall` taking care of matching the function name, parsing the args and separators, parsing the closing parenthesis, … would simplify a lot of code like https://github.com/Siteimprove/alfa/blob/master/packages/alfa-css/src/value/color/hsl.ts#L163 which is essentially duplicated in a few places.

**Comment by kasperisager** [comment]
The first point has been dealt with in #295. I do agree on the second point as well, though the situation in CSS is... complicated. "Functional notation" in CSS isn't the same as "function calls" in the sense that we're used to from programming languages. While the latter is most often some variant of "function name followed by zero or more arguments separated by some token", the former is really just "function name followed by _stuff_". In the past, this "stuff" has mostly been "zero or more components separated by a comma" but the various CSS specifications are in the process of moving to comma-free syntaxes for functional notation, with commas only being used for disambiguation purposes: https://wiki.csswg.org/ideas/functional-notation

The best thing we can do is therefore probably something along the lines of:

```ts
function parseFunctional<T>(values?: Parser<Slice<Token>, T, string>): Parser<Slice<Token>, T, string>;
```

This combinator would parse a function name, zero or more components, and a closing parenthesis and then apply the `values` parser to the parsed components.
