### ISSUE TITLE
Differentiate between static and focusable separators

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#366]
The `separator` role (https://w3c.github.io/aria/#separator) has different requirements depending on whether the element carrying the role is focusable or not. There might not be a good way to encode this within the current structure of `Role` instances, so this may be something we should cater to at the rule level instead.

**Comment by Jym77** [comment]
Given that even the superclass role is different 🤯 it looks as if there are actually 2 `separator` roles which somehow happen to have the same name… (is it something we should report to ARIA and pray they change it before 1.2 make it to Recommendation?)
Of course, when fetching data directly from ARIA, it's hard to make that separation internally without some dirty hack during fetch/build… 😞 

I'm not super fan of handling this at rule level as it requires some extra check with little way to remember it, thus adding burden on rule writing every time… It's fairly OK to hack the existing rules about requirements, but we're bound to forget about this next time we write a rule. A hacky fetch would at least be documented and we'll remember why it's needed.

**Comment by kasperisager** [comment]
The correct(tm) solution would indeed be separating, pun perhaps intended, the `separator` role in two; one role for widget version, and one role for the structure version. I'm however afraid that that won't happen any time soon even if the ARIA WG is on board with the idea, so for now I'll short-circuit the attribute check in R16. Yes, it's a hack, but it's the smallest possible hack that will do the trick. Seeing how R16 is the only rule that needs to deal with required attributes, I'm fine with an isolated hack that is easy to get rid of.
