### ISSUE TITLE
Investigate accessible name fallback after valid but empty `aria-labelledby`

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#389]
https://act-rules.github.io/rules/ffd0e9#failed-example-1
```html
<span id="label"></span>
<h1 aria-labelledby="label">ACT rules</h1>
```
The IDref does exist but when processing it for name results in an empty name.
It is not fully clear in the specs that step 2B should continue in that case (if the IDref exists, it is processed and returned, comparatively step 2C is explicit about `aria-label` not being empty).

In our current implementation, that step returns an empty value and `fromSteps` thus continue to the next step.
See also https://github.com/act-rules/act-rules.github.io/issues/1203

(looks like with the previous implementation of accessible name, we did exit early in that case)

**Comment by kasperisager** [comment]
The current behaviour aligns with Firefox and Safari so Chrome seems like the odd one out. Let's keep an eye on https://github.com/w3c/accname/issues/72.

**Comment by kasperisager** [comment]
I opened w3c/accname#112 to solve this, which may or may not be accepted 🤷
