### ISSUE TITLE
SIA-R46 should not apply to cells in presentational tables

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#390]
https://act-rules.github.io/rules/d0f69e#inapplicable-example-7
```html
<table role="presentation">
	<tr>
		<th>Time</th>
	</tr>
	<tr>
		<td>12:00</td>
	</tr>
</table>
```

The ACT rule requires the table to be included in the accessibility tree.
SIA-R46 uses `isPerceivable` which checks whether an inclusive descendant is included in the accessibility tree.

The `<th>` element is indeed exposed, making the case Applicable for Alfa…

**Comment by kasperisager** [comment]
Good catch! The only requirement for the containing `table` or `grid` is indeed that it's included in the accessibility tree and so the `isIgnored()` predicate should be used rather than `isPerceivable()`.
