### ISSUE TITLE
Improve comparison of URLs in rules

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#420]
Several rules need to compare documents referred by URLs (either destinations of links, content of `<iframe>`, or possibly other). Comparison is currently done by crude comparison of the string.
That consider as different URLs that resolve to the same page, such as trailing slash, relative vs absolute path to the same resource, …

The behaviour can be improved, likely by converting the URL through use of `URL` and would reduce the number of questions asked to the user.
Some work in that direction for R15 is done in #406.

Other rules that are affected include R41 and R81.
There might be a need to know the URL of the current document in order to correctly resolve relative URLs…

**Comment by kasperisager** [comment]
> There might be a need to know the URL of the current document in order to correctly resolve relative URLs.

That's already available as `Page#response.url`.

**Comment by kasperisager** [comment]
A needed piece for this was introduced in #421.
