### ISSUE TITLE
Follow the recommended community standards

### ISSUE THREAD

**Issue by NiclasHedam** [Siteimprove/alfa#44]
GitHub published a set of [recommendations](https://opensource.guide/) for a healthy open source project. Of the recommendations, we are lacking three;

- [x] Description
- [x] README
- [x] Code of conduct
- [x] Contributing
- [x] License
- ~~Issue templates~~
- ~~Pull request template~~

I think it makes good sense to write these soon, as it helps both contributors and maintainers in making a good and efficient contribution.

**Comment by kasperisager** [comment]
I'll be working on contribution guidelines in the not too distant future 👍 At this point in time, we can't foresee what we might want people to include in an issue or a pull request though, so we'll hold off on issue and pull request templates for now.

**Comment by NiclasHedam** [comment]
Is there any news on the contribution guidelines?

**Comment by kasperisager** [comment]
Not yet, and I'm afraid I'll be swamped until sometime mid November.
