### ISSUE TITLE
Coverage warnings are missing for completely untested files

### ISSUE THREAD

**Issue by NiclasHedam** [Siteimprove/alfa#49]
When running `yarn test`, the build system notifies the builder about any files with a coverage lower than 90%. Unfortunately, it completely ignores files that are entirely untested, as it never invokes the coverage suggestion tool. The aforementioned gives an incorrect overview of the coverage and should be corrected.

**Comment by NiclasHedam** [comment]
An issue could be to detect which files can't be tested such as `/packages/alfa-crypto/src/types.ts`.

**Comment by kasperisager** [comment]
The simple approach is to add en empty spec file for all the files that need tests. No magic, no complicated code, just conventions 👍

**Comment by NiclasHedam** [comment]
Do you mean manually adding the spec files? I think that will be forgotten and overlooked in the long run - that is why I want to create an automatic solution.

**Comment by kasperisager** [comment]
Combining the two approaches is where the benefit lies; have the build system complain about missing spec files and then leave it at that. Every implementation file then needs an associated spec file, but the spec files can be empty if needed.

**Comment by kasperisager** [comment]
@NiclasHedam That's not always the case. Consider this:

```ts
enum Whatever {
  Foo = 1,
  Bar = 2,
  Baz = 3,
  Qux = Flags.Foo + Flags.Bar
}
```

We'd never want to test the above even though it includes arithmetic.
