### ISSUE TITLE
SIA-R10 should not apply to disabled inputs

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#516]
R10 is passing https://act-rules.github.io/rules/73f2c2#inapplicable-example-6
This is likely due to the fact that R10 looks literarily at the presence of an `aria-disabled` attribute on the element: https://github.com/Siteimprove/alfa/blob/master/packages/alfa-rules/src/sia-r10/rule.ts#L37
rather than on the value of the property which could be set by the HTML `disabled` attribute.

This could result in false positives in case of bad autocomplete on a disabled field.

**Comment by kasperisager** [comment]
This matches the current applicability of the ACT-R rule, though I'm not sure why it only calls out `aria-disabled` 🤷 https://act-rules.github.io/rules/73f2c2#applicability

**Comment by kasperisager** [comment]
Shoot, it's hiding behind the definition "attribute value":

> For `aria-*` attributes, the attribute value is computed as indicated in the WAI-ARIA specification.

That definition isn't correct though; WAI-ARIA doesn't specify how native attributes are mapped to ARIA semantics, the AAMs are.

**Comment by Jym77** [comment]
The underlying question is whether we should do a local fix of ignoring `disabled` elements here, or a more global fix of having (let's say) a declared and computed value of attributes, especially the `aria-*` ones, and have this rule query the computed value of `aria-disabled` (rather than it's declared value).

**Comment by kasperisager** [comment]
What should happen here is that the rule should query the accessibility tree for the value of the `aria-disabled` state.
