### ISSUE TITLE
Line numbers are incorrectly formatted in coverage suggestions on Windows

### ISSUE THREAD

**Issue by Bugvi-BM** [Siteimprove/alfa#52]
Currently, the test output on windows is bugged. Specifically, the line numbers are incorrect and only display the last digit in the number, e.g 101 will display as 1.

**Comment by NiclasHedam** [comment]
This issue is vague for anyone who has not seen the bug in action. You could provide a screenshot, maybe?

**Comment by Bugvi-BM** [comment]
![image](https://user-images.githubusercontent.com/38207818/45683636-7468de00-bb44-11e8-83da-992ea556f533.png)

**Comment by Bugvi-BM** [comment]
Issue persists even when using cmder terminal emulator.
