### ISSUE TITLE
SIA-R63 does not account for the MIME type of embedded content

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#522]
It looks like we've missed this update: https://github.com/act-rules/act-rules.github.io/pull/1441/files#diff-45a80322b00d896701292ffb014b704baee1eae2e7fffd5d72d2d88698f029eeR26

Not sure how we can detect MIME type of the embedded content 🤔

**Comment by kasperisager** [comment]
We can't 🙈

**Comment by kasperisager** [comment]
Closing as this is not something we can support.
