### ISSUE TITLE
Truncation of coverage suggestion output

### ISSUE THREAD

**Issue by Bugvi-BM** [Siteimprove/alfa#53]
The test output should be formatted such that large blocks are truncated. In addition, if one of the suggested uncovered blocks is really large, the number of blocks outputted should be cut down.

**Comment by NiclasHedam** [comment]
I do not agree that blocks should be truncated. Truncating parts of the block could remove the critical statements from the block and make it look unimportant and not necessary to test.

**Comment by NiclasHedam** [comment]
I have created a PR for the last suggestion. It will now only print as many blocks as there is room for.
See  #56.
