### ISSUE TITLE
Implement support for An+B microsyntax

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#57]
Pseudo-class selectors currently only support values that are either selectors or lists of selectors:

https://github.com/Siteimprove/alfa/blob/27e4ccc3a9da94ab936715b12034fc23ddd74648/packages/alfa-css/src/types.ts#L109

However, some functional pseudo-class selectors make use of the An+B microsyntax (https://www.w3.org/TR/css-syntax/#anb), for example `:nth-child(2n+1)`. To support these kinds of selectors, we first need to implement support for this syntax within the selector parser. The lexer can already lex them:

https://github.com/Siteimprove/alfa/blob/27e4ccc3a9da94ab936715b12034fc23ddd74648/packages/alfa-css/test/alphabet.spec.ts#L335-L349

**Comment by Bugvi-Benjamin-M** [comment]
@2biazdk has been working on this for some time but has been caught up with other stuff that has prevented him from making progress lately. We are going to take a look at this soon.

**Comment by kasperisager** [comment]
Reopening as support will need to be reintroduced following #165.
