### ISSUE TITLE
Residency of alfa-bench code

### ISSUE THREAD

**Issue by NiclasHedam** [Siteimprove/alfa#59]
Alfa-bench is as of today a separate package, which I think is questionable. The intent of the benchmark tool is for developers and contributors of alfa to benchmark parts of the codebase. For that reason, I think it makes more sense to let the benchmark toolset reside in a separate folder in the root or scripts.

One gain of detaching alfa-bench is that it will then be exempt from all coverage requirements.

**Comment by kasperisager** [comment]
The package needs to participate in the build process similar to `alfa-test` and for that reason must be a stand-alone package. Packages like these can be regarded as "internal" and do not have to be published (`private: true`), but should still meet the same requirements as "external" packages in terms of test coverage and code quality.

**Comment by NiclasHedam** [comment]
Thank you for the clarification. If this is the case, I suggest a naming convention, that explicitly states this, as all packages are currently considered private.
A convention could be `internal-test` or `alfa-internal-test`
