### ISSUE TITLE
Update SIA-R62 according to latest ACT-R draft

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#668]
The ACT-R rule that SIA-R62 builds on (https://github.com/act-rules/act-rules.github.io/pull/1010) has changed quite substantially since we first implemented it. In fact, it should now be possible to provide a fully automated implementation of this rule. While the rule hasn't been published yet, we should consider updating our implementation according to the latest draft as soon as time allows.

#710 and #709 are needed for this, though we might be able to do with just of subset of those properties.

- [ ] Follow up on DEV-11431.

**Comment by Jym77** [comment]
Actually, we want to apply to any link, disregarding the **different hue** condition from ACT rules. So Applicability shouldn't need to change.
