### ISSUE TITLE
Set up Continous Integration

### ISSUE THREAD

**Issue by NiclasHedam** [Siteimprove/alfa#7]
I think it would make good sense to set up automatic testing for alfa. As the project is open source, we could set up travis-ci for free to run `npm test` or `foreman build/test.ts`.

**Comment by kasperisager** [comment]
Absolutely! I however need to have a chat with IT and Operations about the specifics of it as we cannot just willy nilly choose a provider and give them read-access to the @Siteimprove org 👍

**Comment by WilcoFiers** [comment]
I can also highly recommend setting up Greenkeeper. There's so much cool stuff you can get for free with OS ;-)

**Comment by kasperisager** [comment]
IT is currently reviewing Semaphore CI (https://semaphoreci.com/).
