### ISSUE TITLE
SIA-R87 should automatically pass links that target descendants at the very beginning of a `main` landmark

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#706]
SIA-R87 currently requires external input to determine if the following case passes:

```html
<a href="#content">Skip to content</a>

<main>
  <div id="content">
    <p>This is the content</p>
  </div>
</main>
```

Another variation is this:

```html
<a href="#content">Skip to content</a>

<main>
  <div id="content"></div>
  <p>This is the content</p>
</main>
```

It also isn't unthinkable that we might encounter cases like this:

```html
<a href="#content">Skip to content</a>

<div id="content">
  <main>
    <p>This is the content</p>
  </main>
</div>
```

Or even this:

```html
<a href="#content">Skip to content</a>

<div id="content"></div>
<main>
  <p>This is the content</p>
</main>
```

- [ ] Follow up on DEV-11237.

**Comment by Jym77** [comment]
https://act-rules.github.io/glossary/#just-before 😀 (link goes "just before" the first perceivable content in `main`).

**Comment by kasperisager** [comment]
If we let `P` be the first perceivable descendant of the `main` landmark then that should do the trick 👏

**Comment by kasperisager** [comment]
We need a method for getting the [lowest common ancestor](https://en.wikipedia.org/wiki/Lowest_common_ancestor) of two nodes as well. If we start the traversal at the lowest common ancestor, we should be able to skip traversing the first bit of the document in a lot of cases.
