### ISSUE TITLE
Increase test coverage of `alfa-dom` to 90%

### ISSUE THREAD

**Issue by Bugvi-Benjamin-M** [Siteimprove/alfa#72]

**Comment by kasperisager** [comment]
What's the status on this?

**Comment by Bugvi-BM** [comment]
Currently on hold. But I will continue with it after my current adventure with comments and TODO lists


[Perfect Your Digital Presence]



Búgvi Benjamin Magnussen
Student Developer


[Siteimprove]<http://siteimprove.com/da/>


Sankt Annæ Plads 28  |  DK-1250 København K
bbm@siteimprove.com<mailto:bbm@siteimprove.com>


Facebook<https://www.facebook.com/Siteimprove>   Twitter<https://twitter.com/Siteimprove>   LinkedIn<https://www.linkedin.com/company/siteimprove>


Unsubscribe<http://go.siteimprove.com/hs/manage-preferences/unsubscribe-simple>


________________________________

**Comment by kasperisager** [comment]
Closing this in favor of smaller, incremental additions to the test suite.
