### ISSUE TITLE
`isClippedBySize()` does not account for cases where the grandparent of a text node fully indents and clips text

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#731]
`isClippedBySize()` currently returns `false` for the following text node:

```html
<style>
  div {
    overflow-x: hidden;
    text-indent: 100%;
    white-space: nowrap;
  }
</style>

<div>
  <span>This is invisible</span>
</div>
```

- [ ] Follow up on DEV-11338.

**Comment by kasperisager** [comment]
Adjusted the title and description to clarify the _issue_ at hand, not the proposed solution. The issue with simply looking further up the tree for a computed `overflow-x` is that, for some reason, many pages declare `overflow-x: hidden` near the document root (`<body>` or `<html>`).

For lack of a layout system, I'd rather we assume that `text-indent: -100%` or `text-indent: 100%; white-space: nowrap` means that the text will be invisible, regardless of `overflow-x`. There might be other pitfalls to that so let's examine those a little further at a refinement.
