### ISSUE TITLE
SIA-R62 shouldn't ask questions for states it can automatically resolve

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#733]
https://github.com/Siteimprove/alfa/blob/454838a6570063eedc3db7bedc4576ddddcf387d/packages/alfa-rules/src/sia-r62/rule.ts#L78-L109
As far as I can tell, if one of the 3 `isDistinguishable` is false, Alfa is going to ask the 3 questions, even though it might already know that the 2 others `isDinstinguishable` are true. This creates needless questions for user.

This might become irrelevant with #668 if R62 becomes fully automated.

**Comment by kasperisager** [comment]
Closing in favour of #668 which will completely remove these questions.
