### ISSUE TITLE
SIA-R66 and SIA-R69 do not account for backgrounds positioned underneath text and vice versa

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#758]
The following code incorrectly fails both rules despite rendering white text on a black background:

```html
<!DOCTYPE html>

<style>
  div,
  p {
    position: relative;
  }

  span {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-color: black;
  }

  p {
    color: white;
  }
</style>

<div>
  <span></span>
  <p>Hello world</p>
</div>
```

```html
<!DOCTYPE html>

<style>
  div,
  p {
    position: relative;
  }

  div::before {
    content: "";
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-color: black;
  }

  p {
    color: white;
  }
</style>

<div>
  <p>Hello world</p>
</div>
```

- [ ] Follow up on DEV-11398.
- [ ] Follow up on DEV-11445.
- [ ] Follow up on DEV-11472.
- [ ] Follow up on DEV-11520.
- [ ] Follow up on DEV-11615.
- [ ] Follow up on DEV-11716.
- [ ] Follow up on DEV-11704.
- [ ] Follow up on DEV-11757.
- [ ] Follow up on DEV-11770.
- [ ] Follow up on DEV-11933.
- [ ] Follow up on DEV-11963.
- [ ] Follow up on DEV-12121.
- [ ] Follow up on DEV-12244.

**Comment by Drejz** [comment]
Adding https://siteimprove-wgs.atlassian.net/browse/DEV-11615 to the list of follow ups :)

**Comment by Jym77** [comment]
Specific case seen in DEV-11770 where the background image is set on a `:after` pseudo-element.
We have poor support of pseudo-element (never matching anything). So it might need special treatment…

**Comment by kasperisager** [comment]
Here's an approach I'll investigate the effect of: Assume that positioned backgrounds, that is background colors or images applied to positioned elements with no content, become backgrounds for the subtree rooted at their offset parent.

**Comment by Jym77** [comment]
Yes, that could work.
We probably want to still always return `cantTell` when finding one of these (even if it's a solid background) to avoid assuming too much.

**Comment by kasperisager** [comment]
Looking into the linked support tickets, this solves all but 1 case: Text absolutely positioned over an `<img>` element. I've adjusted the issue title to reflect this situation.
