### ISSUE TITLE
Text inside element with role="presentation" is omitted from Accessible Name

### ISSUE THREAD

**Issue by 2biazdk** [Siteimprove/alfa#769]
It seems that Alfa completely disregards contents of an element with `role="presentation"` when it comes to calculating an Accessible Name.

`<button><span role="presentation">Text</span></button>` is flagged as having no Accessible Name, even though `role="presentation"` is only supposed to remove the semantics (if any) from the node. `role="presentation"` isn't inherited to child nodes. Chrome's DevTools also seems to tell me that the button has the Accessible Name "Text".

**Comment by Jym77** [comment]
Closing this in favour of the more generic #776
