### ISSUE TITLE
Compilation sometimes fails during CI due to excessive memory consumption

### ISSUE THREAD

**Issue by NiclasHedam** [Siteimprove/alfa#77]
This issue looks like it is caused by Semaphore timing out or crashing.

**Comment by NiclasHedam** [comment]
A solution could be not to compile the Unicode dataset each time; it could be something to do in a `version` hook.
Also, `packages/alfa-unicode/scripts/characters.js` seemingly has a hardcoded Unicode version number, so downloading and compiling the same dataset on each commit is just a waste of CPU cycles.

**Comment by kasperisager** [comment]
The data set is only fetched when requested locally so the only time consuming task performed during CI is compilation. We however cannot naïvely skip compilation of select files even if they haven't changed as a change to any file within their import graph could affect type checking. 

The best, and safest, approach to speeding up compilation would therefore be to traverse the import graph of all files that have changed within a given commit range during CI and then compile only those files. Off the top of my head, I can't think of better ways to go about incremental compilation at least.

**Comment by kasperisager** [comment]
Semaphore actually output an error message for this one build: https://semaphoreci.com/siteimprove/alfa/branches/todo-list-fix/builds/19. Not surprisingly, the cause is that the process runs out of memory.

**Comment by NiclasHedam** [comment]
That's new! Good to know though.

**Comment by kasperisager** [comment]
> The data set is only fetched when requested locally so the only time consuming task performed during CI is compilation. We however cannot naïvely skip compilation of select files even if they haven't changed as a change to any file within their import graph could affect type checking.
> 
> The best, and safest, approach to speeding up compilation would therefore be to traverse the import graph of all files that have changed within a given commit range during CI and then compile only those files. Off the top of my head, I can't think of better ways to go about incremental compilation at least.

**Comment by kasperisager** [comment]
Fat-fingered the close button 🤦‍♀️

**Comment by kasperisager** [comment]
ff80be7 should hopefully provide a solution to this but we'll see 🤞
