### ISSUE TITLE
SIA-R62 should accept decoration on the parent or child of the link

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#777]
Currently, failing both these links:
```html
<style>
  a {
    text-decoration: none;
  }
  span {
    text-decoration: underline;
  }
</style>

<p>
  Lorem <a href="#"><span>Foo</span></a> Ipsum <span><a href="#">Bar</a></span>
</p>
```
The ACT rule draft (and Sanshikan) accepts both.
https://github.com/act-rules/act-rules.github.io/blob/4b64bba6cb77a8d4dc0649c83c55372f513d979f/_rules/inline-link-in-paragraph-is-distinguishable-be4d0c.md#expectation

We can probably have a good approximation by looking at the properties on the (parent of the) text node(s) inside the link. Might get a bit complex if there are more than one text node, with different properties…

Similarly, we might want to look at style on (parents of) text nodes inside the paragraph since we currently pass
```html
<p style="font-weight: 400">
  <span style="font-weight: 700">Lorem</span>
  <a href="#" style="font-weight: 700; text-decoration: none">Ipsum</a>
</p>
```
because the `<a>` has a different style than the `<p>`… But every text inside the `<p>` actually has the same style as the `<a> 😞 

- [ ] Follow up on DEV-11653.
- [ ] Follow up on DEV-11636.
- [ ] Follow up on DEV-11724.
- [ ] Follow up on DEV-11987.

**Comment by offsetChris** [comment]
Hi @Jym77 I just had this situation come up on a review call. This is the example of an error that I believe is not an error. It seems like this situation would be covered by this bug and solution, but wanted to throw this use case at you too. 

`<p style="font-weight:normal;"><a href="#"><strong>Bolded anchor text</strong></a> paragraph text with non bold font weight.</p>`

**Comment by Jym77** [comment]
@offsetChris yes, that's typically the case we need to handle.

**Comment by kasperisager** [comment]
We need to be incredibly mindful of the performance implications of implementing this.

**Comment by Jym77** [comment]
> We need to be incredibly mindful of the performance implications of implementing this.

Yes…

What I'm considering is whether it makes sense to look at the style not on the link but on the parent of the text node inside the link. As far as I can tell, this should be the style which is actually used to show the text, so it should be good. And it shouldn't be too high on complexity (we just need to go down the DOM tree).

This does open a can of worms of what happens when there are several of these, but this can is somewhat already open once we need to decide whether `<a href="#" class="no-decoration"><span class="decoration">Hello</span> World</a>` is good or not…

The same trick could be used for the style of the non-link text by looking at parent of text nodes that are descendant of the paragraph but not of the link… I've seen stuff like `<p><div class="bold">Lorem<a href="#" class="bold">Ipsum</a></div></p>` which technically passes the rule since the style of the `<p>` is not bold and thus differ from the style of the `<a>`… Even though all the actual text inside the paragraph is bolded…

**Comment by Jym77** [comment]
We can compare the style of the (parent of) the text nodes and pass if at least one style is different between the link and the surrounding paragraph.
To limit the complexity, we need to compute the styles of each text node, so we can collapse identical styles; so we avoid comparing all pair of text nodes but rather compute pairs of styles, which we assume are much less numerous.

The styles can e summed up as the diagnostic object which is already used...
