### ISSUE TITLE
Accessible name shouldn't use parent `<label>` if it has a `for` attribute

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#781]
Alfa is giving an accessible name to `input1`, neither Chrome nor Firefox do. We're probably not checking `for` attribute of ancestor `<label>`…
```html
  <form>
    <label for="input2">
      <input id="input1" />
      Hello world
    </label>

    <input id="input2" />
  </form>;
```
…because why write clean code?

**Comment by kasperisager** [comment]
`for` should take precedence as per HTML: https://html.spec.whatwg.org/multipage/forms.html#attr-label-for
