### ISSUE TITLE
SIA-ER62 should accept a difference in contrast of 3:1 or more as valid indicator

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#796]
We left that on the side when initially writing the rule, for the sake of simplicity (https://github.com/Siteimprove/alfa/pull/538#issuecomment-725428875). I have seen this week 3 feedbacks about this being incorrect, each pointing to [G183 ](https://www.w3.org/TR/WCAG20-TECHS/G183.html)(so I guess each from accessibility experts…)

So, it is maybe time for us to consider improving the rule…

- [ ] Follow up on DEV-12271.
- [ ] Follow up on DEV-12416.
- [ ] Follow up on DEV-12447.

**Comment by kasperisager** [comment]
The rule should accept a difference in contrast *if* we can automatically determine the foreground colors. When we can't, we won't accept color as an indicator.

**Comment by zsofitoth** [comment]
Specification: https://www.w3.org/TR/WCAG20-TECHS/G183.html
