### ISSUE TITLE
Bad error message in resolve-style.ts

### ISSUE THREAD

**Issue by NiclasHedam** [Siteimprove/alfa#81]
https://github.com/Siteimprove/alfa/blob/master/packages/alfa-css/src/resolve-style.ts#L198
This is probably not the error message we are looking for.

**Comment by kasperisager** [comment]
[<img src=https://upload.wikimedia.org/wikipedia/commons/f/f6/HAL9000.svg width=48 alt="HAL 9000">](https://en.wikipedia.org/wiki/HAL_9000)
