### ISSUE TITLE
SIA-R75 should ignore elements with no text depending on their font size

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#810]
```html
<div style="font-size: 1px">
  <span style="font-size: 16px">Hello World</span>
</div>
```

Alfa currently fails the `<div>` but shouldn't since it doesn't have text content that depends on its `font-size`…

- [x] Depends on Siteimprove/sanshikan#176
- [ ] Follow up on DEV-11898

**Comment by kasperisager** [comment]
This is a little more involved than it might seem. We'll effectively have to keep track of which font sizes influence due to the existence of relative font sizes. Consider this:

```html
<div style="font-size: 1px">
  <span style="font-size: 1em">Hello World</span>
</div>
```

**Comment by kasperisager** [comment]
My bad; pressed the wrong button 🤦

**Comment by kasperisager** [comment]
The rule should be looking at the individual text nodes and check their computed font size.
