### ISSUE TITLE
Parse integer according to HTML specification (i.e. ignores trailing non-digits)

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#813]
As per specs, `tabindex` [must be a valid integer](https://html.spec.whatwg.org/multipage/interaction.html#attr-tabindex).

However, it seems that Chrome is a bit more lax in parsing it and parses `tabindex="-1-"` (extra dash) as "-1" while Alfa sees the extra dash as an error (according to specs) and default to 0.
![tabindex](https://user-images.githubusercontent.com/19969498/119468518-d0994c80-bd46-11eb-8359-7c8addeab730.png)

We should consider whether we want to stick with the specs or follow suit with browser (also investigate what other browsers are doing).

Reference: https://github.com/Siteimprove/alfa/blob/20b58b5e55271026eef7984b05c205512ccb18b6/packages/alfa-dom/src/node/element.ts#L228

- [ ] Follow up on DEV-11797

**Comment by kasperisager** [comment]
Let's compile a list of results for the current browsers supported (Chrome, Firefox, and Safari) and make a decision then.

**Comment by Jym77** [comment]
While the definition of [valid integer](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-integer) rejects non-digits, the actual [rules for parsing](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#rules-for-parsing-integers) (point 8) stop with success at the first non-digit (thus `-1-` does parse as `-1`).

We should update our parsing algorithm to handle that…

**Comment by Jym77** [comment]
Can take inspiration for parsing from [`getRefreshTime`](https://github.com/Siteimprove/alfa/blob/main/packages/alfa-rules/src/common/expectation/get-refresh-time.ts)
