### ISSUE TITLE
SIA-R62 should accept superscript and subscript as distinguishing features

### ISSUE THREAD

**Issue by offsetChris** [Siteimprove/alfa#823]
I'm wondering what the team thinks of the following use case for distinguishable links in paragraph text. I'm leaning towards the treatment of a `<sup>` or `<sub>` tag being sufficient to distinguish the link but open to having a conversation. Also more generally wondering if positioning of the link should be considered as a distinguishing characteristic. That might be too variable and more suitable for a manual confirmation but curious of your thoughts.

Example: A link as a superscript footnote where underline might make this illegible. 
`<p>This is important paragraph text that requires a footnote. <sup><a href="#footnote">[1]</a><sup><p>`

**Comment by Jym77** [comment]
2 separate points here:
* I agree that `<sap>` and `<sub>` are a big enough difference to indicate links, and this is a very practical case. They seem to do their magic through the `vertical-align` CSS property (https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3) which looks easy to support (keyword, length, percentage).
* There is the question of detecting the style set not on the `<a>` element but on its parent or child. We currently don't handle that but definitely need to (#777).

**Comment by offsetChris** [comment]
Awesome! Thanks @Jym77! Let me know if I can help in any way!

**Comment by kasperisager** [comment]
Add support for `vertical-align` and add this to our UA style sheet (https://github.com/Siteimprove/alfa/blob/main/packages/alfa-cascade/src/user-agent.ts):

```css
sub { vertical-align: sub; }
sup { vertical-align: super; }
```
