### ISSUE TITLE
Absolutely positioned elements are able to escape their clipping ancestor

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#824]
```html
<style>
  .clipping {
    overflow: hidden;
    height: 28px;
    border: red solid;
    margin: 20px;
  }
  .absolute {
    position: absolute;
  }
</style>

<div class="clipping">Lorem ipsum…</div>

<div class="clipping">
  <div class="absolute">Lorem ipsum…</div>
</div>
```

R83 flags both text, but the absolute positioning on the second actually let it escape the clipping.

![clipped](https://user-images.githubusercontent.com/19969498/120787790-04872580-c530-11eb-9f3a-1c7c2e6cb95f.png)

As far as I understand, the absolutely positioned element has a 0-sized box in the normal flow (and that box is inside the clipping ancestor), and then another box, in another stacking context, is created for it (and placed where it should). The box which actually has content is not part of the same stacking context as the clipping box, so it can overflow it freely…

**Comment by Jym77** [comment]
Should be fixable by escaping `isPossiblyClipped` whenever we find an absolutely positioned element (or any element creating a new stacking context).

**Comment by kasperisager** [comment]
This goes deeper than just `position: absolute` and forces us to deal with offset parents. Consider this:

```html
<!DOCTYPE html>

<style>
  .clipping {
    position: relative;
    overflow: hidden;
    height: 28px;
    border: red solid;
    margin: 20px;
  }
  .absolute {
    position: absolute;
  }
</style>

<div class="clipping">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit [...]
</div>

<div class="clipping">
  <div class="absolute">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit [...]
  </div>
</div>
```

Both texts now clip due to `.relative` being the offset parent of `.absolute`.

**Comment by kasperisager** [comment]
To summarise:

1. When looking for a clipping ancestor, check:
    1. If the current element is statically positioned and clips, done. If it does not clip, keep looking.
    2. If the current element is *not* statically positioned, skip all ancestors until the offset parent and keep looking.
