### ISSUE TITLE
`Name.fromDescendant()` should reject empty spaces names

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#830]
```html
<a href="#" title="Hello world">
      <span> </span>
</a>
```
Receives ` ` (space) instead of `Hello world` as a name, because the content takes precedence and `Name.fromDescendant()` returns `Some " "` rather than `None`.
Both Chrome and Firefox give `Hello World` as name.

- [ ] Follow up on DEV-11839
- [ ] Follow up on DEV-11885

**Comment by kasperisager** [comment]
@Jym77 Will you follow up on the Jiras if that isn't already on your list?

**Comment by Jym77** [comment]
Good call. Forgot these 😓 Will do.
