### ISSUE TITLE
SIA-R62 should accept difference in `cursor` as distinguishable

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#845]
Depends on #844

- [ ] Follow up on DEV-12304.

**Comment by kasperisager** [comment]
Holding off on this until #875 has landed.

**Comment by Jym77** [comment]
To detect difference in `cursor`, we'll consider that the first value in the list is always the correct one (no fallback to default value in case the image is not found), and accept any difference in the URL.

At first, let's rejects differences solely in the offsets. It seems a bit too crazy of a use case to be really meaningful.
