### ISSUE TITLE
`clip` should only apply to absolutely positioned elements

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#847]
As per specs 😖 https://drafts.fxtf.org/css-masking-1/#clip-property

Easy fix should be to update `compute` so that it returns `auto` (the initial value) if the element's `position` is neither `absolute` nor `fixed`.

**Comment by Jym77** [comment]
We actually do check it there: https://github.com/Siteimprove/alfa/blob/main/packages/alfa-rules/src/common/predicate/is-clipped.ts#L136
But this is probably not the best place to do so…

**Comment by kasperisager** [comment]
Adjust https://github.com/Siteimprove/alfa/blob/20b58b5e55271026eef7984b05c205512ccb18b6/packages/alfa-style/src/property/clip.ts#L46 as per @Jym77's comment.
