### ISSUE TITLE
SIA-R18 should accept attributes allowed by ARIA in HTML

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#856]
See https://github.com/Siteimprove/sanshikan/pull/185

https://www.w3.org/TR/html-aria/#docconformance

- [ ] Follow up on DEV-12322

---
- [ ] `<body>` accepts attributes allowed on `document` role;
- [ ] `<input>` with type `date`, `datetime-local`, `email`, `month`, `password`, `time`, `week`  accept attributes allowed on `textbox` role;
- [ ] `<select>` with no `multiple` and no `size` greater than 1 (i.e. display size of `1`) accepts attributes allowed on `combobox` and `menu` roles.
- [ ] `<video>` accepts attributes allowed on the `application` role.

**Comment by kasperisager** [comment]
Those attributes are already mapped via the accessibility tree that R18 looks at, so I'm not sure if there's anything else we need to do?

**Comment by Jym77** [comment]
Nope.
```javascript
test(`evaluate() passes a password field with aria-required state`, async (t) => {
  const target = <input type="password" aria-required="true" />;

  const document = h.document([target]);

  t.deepEqual(await evaluate(R18, { document }), [
    passed(R18, target.attribute("aria-required").get(), {
      1: Outcomes.IsAllowed,
    }),
  ]);
});
```

fails.

`<input type="password" />` has no role ([HTML AAM](https://www.w3.org/TR/html-aam-1.0/#details-id-66)) so R18 only accepts global attributes, which `aria-required` is not. But [ARIA in HTML](https://www.w3.org/TR/html-aria/#el-input-password) allows `aria-required` on `<input type="password" />`…

**Comment by kasperisager** [comment]
Oh, I got the two mixed up 🤦 That's indeed not solved for yet, no 👌

**Comment by kasperisager** [comment]
Let's deal with this in the rule initially and then figure out if there's a better place to put it, such as https://github.com/Siteimprove/alfa/blob/main/packages/alfa-aria/src/feature.ts.
