### ISSUE TITLE
`isClipped()` does not account for offset parents

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#887]
Same situation as with #824, just for the `isClipped()` predicate.

**Comment by kasperisager** [comment]
Reference: https://github.com/Siteimprove/alfa/blob/20b58b5e55271026eef7984b05c205512ccb18b6/packages/alfa-rules/src/common/predicate/is-clipped.ts#L39-L46

**Comment by Jym77** [comment]
When fixing it in #964 we forgot to actually call `getPositioningParent` (or `has PositioningParent`) from `isClipped` 🙈
