### ISSUE TITLE
Parallelize package builds across available cores

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#92]
With the changes introduced in  ff80be7, packages no longer use a shared workspace when performing full builds. As such, we now have the option to parallelize package builds across the available cores of the host system. By using the [cluster module](https://nodejs.org/api/cluster.html), we can create a number of process forks, each of which will handle the compilation of packages handed to them by the master process. 

Do be aware of dependencies between packages! Hint: https://cs.stackexchange.com/questions/2524/getting-parallel-items-in-dependency-resolution/2525#2525

**Comment by Bugvi-BM** [comment]
If you will let me, I would love to have a look at this. If only to give a shot, fail miserably and have a few laughs.

**Comment by kasperisager** [comment]
Go for it! 👍

**Comment by kasperisager** [comment]
This may or may not be impacted by #98.

**Comment by kasperisager** [comment]
Putting this on hold for now.

**Comment by kasperisager** [comment]
In light of #170 I'll close this.

**Comment by kasperisager** [comment]
This is now part of the TypeScript 3.9 iteration plan: https://github.com/Microsoft/TypeScript/issues/30235
