### ISSUE TITLE
Consider following ARIA 1.2 once it gets to RECOMMENDATION status

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#958]
Back in #728 we decided to track the Editor's draft of ARIA (1.3) rather than the working draft (1.2).
1.2 is now a Candidate Recommendation and hopefully soon a Recommendation.

We should maybe switch back to the stable version once it is not hopelessly outdated. There are some differences between 1.2 and 1.3 (e.g. `aria-level` is allowed on `listitem` in 1.2 but not in 1.3).

Need to investigate to understand a bit more the differences and see what breaks or not…

- [ ] Follow up on DEV-12513

**Comment by Drejz** [comment]
@Jym77 Seems like 1.2 is not W3C recommendation, should we consider doing this soon? 
https://www.w3.org/TR/wai-aria-1.2/

**Comment by Jym77** [comment]
@Drejz Good catch. This was actually done with #1205 when ACT rules moved to ARIA 1.2.
