### ISSUE TITLE
SIA-R75 should not assess font size of superscript and subscript

### ISSUE THREAD

**Issue by offsetChris** [Siteimprove/alfa#971]
Hello! I received another question about superscript and subscript HTML elements causing errors. 

This time the question is if it is reasonable to fail "Font size are not too small" when the font element in question is within a `<sup>` or `<sub>` HTML element. They are by nature smaller than the paragraph font size, but should we still require that textual content to be above 9px computed font size?

**Comment by Jym77** [comment]
Good point. Given that R75 is Best Practice, there is no problem in ignoring these.
Need to think a bit about the correct "ignore" criterion (I'd prefer it to be based on CSS `vertical-align` than just on the HTML element, that needs a bit of investigation).

**Comment by Jym77** [comment]
Let's start by ignoring content of `<sub>`  and `<sup>` elements, and revisit later if other cases occur.
