### ISSUE TITLE
SIA-R84 shouldn't apply to browsing context containers

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#979]
Following the definition from ACT rules: https://act-rules.github.io/rules/0ssw9k#scrollable-element

Also investigate cases where the browsing context container is the only content of an element.

- [ ] Follow up on DEV-12500

**Comment by offsetChris** [comment]
Hi there @Jym77 I just had this come up recently where we are flagging an error for scrollable element not keyboard accessible on an iframe - if I'm reading this definition correctly we will no longer be running this check against iframes, correct?

**Comment by Jym77** [comment]
Correct. We missed that bit from the ACT rule…

**Comment by Jym77** [comment]
Use https://github.com/Siteimprove/alfa/blob/main/packages/alfa-dom/src/node/element/predicate/is-browsing-context-container.ts

Likely as `Element.isBrowsingContextContainer`
